//! Address-preserving arena collection. Payload pointers never change.
//! Power-of-two free lists reuse dead blocks; a bitmap recognizes exact starts.
//! Pre-loop objects and static words are traced as roots, including memo caches.
//! The algorithm follows the repository's reference arena_runtime.wat; this
//! module owns native symbolic instructions and has no reference-runtime import.
const std = @import("std");
const wasm = @import("wasm.zig");
const Error = std.mem.Allocator.Error;

pub fn emit(module: *wasm.Module, arena: wasm.Arena) Error!void {
    try allocate(module, arena);
    try mark(module, arena);
    try collect(module, arena);
}

fn allocate(module: *wasm.Module, arena: wasm.Arena) Error!void {
    const bytes = 0;
    const class = try module.addLocal(arena.allocate, .i32);
    const size = try module.addLocal(arena.allocate, .i32);
    const head = try module.addLocal(arena.allocate, .i32);
    const end = try module.addLocal(arena.allocate, .i32);
    const pages = try module.addLocal(arena.allocate, .i32);
    const bin = try module.addLocal(arena.allocate, .i32);
    const code = [_]wasm.Instruction{
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_eqz },
        .{ .op = .if_ },
        .{ .op = .global_get, .operand = arena.heap },
        .{ .op = .return_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_const, .operand = 0xffffffec },
        .{ .op = .i32_gt_u },
        .{ .op = .if_ },
        .{ .op = .unreachable_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_const, .operand = 2147483632 },
        .{ .op = .i32_gt_u },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 32 },
        .{ .op = .local_set, .operand = class },
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_const, .operand = 19 },
        .{ .op = .i32_add },
        .{ .op = .i32_const, .operand = 0xfffffffc },
        .{ .op = .i32_and },
        .{ .op = .local_set, .operand = size },
        .{ .op = .else_ },
        .{ .op = .i32_const, .operand = 32 },
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_const, .operand = 15 },
        .{ .op = .i32_add },
        .{ .op = .i32_clz },
        .{ .op = .i32_sub },
        .{ .op = .local_set, .operand = class },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .local_get, .operand = class },
        .{ .op = .i32_shl },
        .{ .op = .local_set, .operand = size },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 32 },
        .{ .op = .local_get, .operand = class },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shl },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = bin },
        .{ .op = .local_get, .operand = bin },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_ne },
        .{ .op = .local_get, .operand = class },
        .{ .op = .i32_const, .operand = 32 },
        .{ .op = .i32_eq },
        .{ .op = .i32_and },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_lt_u },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .local_set, .operand = head },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = bin },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 12 },
        .{ .op = .i32_store },
        .{ .op = .else_ },
        .{ .op = .global_get, .operand = arena.heap },
        .{ .op = .local_set, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 65536 },
        .{ .op = .i32_lt_u },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 65536 },
        .{ .op = .local_set, .operand = head },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = end },
        .{ .op = .local_get, .operand = end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_lt_u },
        .{ .op = .if_ },
        .{ .op = .unreachable_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_sub },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = pages },
        .{ .op = .local_get, .operand = pages },
        .{ .op = .memory_size },
        .{ .op = .i32_gt_u },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = pages },
        .{ .op = .memory_size },
        .{ .op = .i32_sub },
        .{ .op = .memory_grow },
        .{ .op = .i32_const, .operand = 0xffffffff },
        .{ .op = .i32_eq },
        .{ .op = .if_ },
        .{ .op = .unreachable_ },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_load },
        .{ .op = .i32_eqz },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_store },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 12 },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_store },
        .{ .op = .local_get, .operand = end },
        .{ .op = .global_set, .operand = arena.heap },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_store },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = bytes },
        .{ .op = .i32_store, .operand = 4 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_store, .operand = 8 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_store, .operand = 12 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_add },
    };
    try module.emitSlice(arena.allocate, &code);
}

fn mark(module: *wasm.Module, arena: wasm.Arena) Error!void {
    const value = 0;
    const index = 1;
    const start = 2;
    const head = try module.addLocal(arena.mark, .i32);
    const code = [_]wasm.Instruction{
        .{ .op = .local_get, .operand = value },
        .{ .op = .i32_const, .operand = 3 },
        .{ .op = .i32_and },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .return_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = value },
        .{ .op = .local_get, .operand = start },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_add },
        .{ .op = .i32_lt_u },
        .{ .op = .local_get, .operand = value },
        .{ .op = .global_get, .operand = arena.heap },
        .{ .op = .i32_ge_u },
        .{ .op = .i32_or },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .return_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = value },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_sub },
        .{ .op = .local_set, .operand = head },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 7 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shl },
        .{ .op = .i32_add },
        .{ .op = .i32_load },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 31 },
        .{ .op = .i32_and },
        .{ .op = .i32_shl },
        .{ .op = .i32_and },
        .{ .op = .i32_eqz },
        .{ .op = .if_ },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .return_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 4 },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_ne },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 8 },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_and },
        .{ .op = .i32_eqz },
        .{ .op = .i32_and },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 8 },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_or },
        .{ .op = .i32_store, .operand = 8 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 8 },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_and },
        .{ .op = .i32_eqz },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 8 },
        .{ .op = .i32_load },
        .{ .op = .i32_store, .operand = 12 },
        .{ .op = .i32_const, .operand = 8 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_store },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 0 },
    };
    try module.emitSlice(arena.mark, &code);
}

fn collect(module: *wasm.Module, arena: wasm.Arena) Error!void {
    const root = 0;
    const floor = 1;
    const head = try module.addLocal(arena.collect, .i32);
    const count = try module.addLocal(arena.collect, .i32);
    const index = try module.addLocal(arena.collect, .i32);
    const end = try module.addLocal(arena.collect, .i32);
    const scratch_end = try module.addLocal(arena.collect, .i32);
    const pages = try module.addLocal(arena.collect, .i32);
    const slot = try module.addLocal(arena.collect, .i32);
    const limit = try module.addLocal(arena.collect, .i32);
    const size = try module.addLocal(arena.collect, .i32);
    const bin = try module.addLocal(arena.collect, .i32);
    const code = [_]wasm.Instruction{
        .{ .op = .local_get, .operand = floor },
        .{ .op = .global_get, .operand = arena.base },
        .{ .op = .i32_lt_u },
        .{ .op = .if_ },
        .{ .op = .global_get, .operand = arena.base },
        .{ .op = .local_set, .operand = floor },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_eqz },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = root },
        .{ .op = .return_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_set, .operand = count },
        .{ .op = .global_get, .operand = arena.heap },
        .{ .op = .local_set, .operand = end },
        .{ .op = .local_get, .operand = end },
        .{ .op = .local_set, .operand = index },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_const, .operand = 7 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_add },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shl },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = scratch_end },
        .{ .op = .local_get, .operand = scratch_end },
        .{ .op = .local_get, .operand = index },
        .{ .op = .i32_lt_u },
        .{ .op = .if_ },
        .{ .op = .unreachable_ },
        .{ .op = .end },
        .{ .op = .local_get, .operand = scratch_end },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_sub },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = pages },
        .{ .op = .local_get, .operand = pages },
        .{ .op = .memory_size },
        .{ .op = .i32_gt_u },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = pages },
        .{ .op = .memory_size },
        .{ .op = .i32_sub },
        .{ .op = .memory_grow },
        .{ .op = .i32_const, .operand = 0xffffffff },
        .{ .op = .i32_eq },
        .{ .op = .if_ },
        .{ .op = .unreachable_ },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 12 },
        .{ .op = .i32_load },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_ne },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = index },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .local_get, .operand = scratch_end },
        .{ .op = .local_get, .operand = index },
        .{ .op = .i32_sub },
        .{ .op = .memory_fill },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_ge_u },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 7 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shl },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = slot },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_load },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shr_u },
        .{ .op = .i32_const, .operand = 31 },
        .{ .op = .i32_and },
        .{ .op = .i32_shl },
        .{ .op = .i32_or },
        .{ .op = .i32_store },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = head },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 12 },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_store },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 8 },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_store },
        .{ .op = .i32_const, .operand = 256 },
        .{ .op = .local_set, .operand = slot },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .global_get, .operand = arena.static_end },
        .{ .op = .i32_ge_u },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_load },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = count },
        .{ .op = .call, .operand = arena.mark },
        .{ .op = .drop },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = slot },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = head },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = floor },
        .{ .op = .i32_ge_u },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_add },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = count },
        .{ .op = .call, .operand = arena.mark },
        .{ .op = .drop },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = head },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .local_get, .operand = root },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = count },
        .{ .op = .call, .operand = arena.mark },
        .{ .op = .drop },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .i32_const, .operand = 8 },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_eqz },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .i32_const, .operand = 8 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 12 },
        .{ .op = .i32_store },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 16 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = slot },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 4 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = limit },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_const, .operand = 3 },
        .{ .op = .i32_add },
        .{ .op = .local_get, .operand = limit },
        .{ .op = .i32_ge_u },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_load },
        .{ .op = .local_get, .operand = index },
        .{ .op = .local_get, .operand = count },
        .{ .op = .call, .operand = arena.mark },
        .{ .op = .drop },
        .{ .op = .local_get, .operand = slot },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = slot },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .i32_const, .operand = 4 },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = head },
        .{ .op = .block },
        .{ .op = .loop },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = end },
        .{ .op = .i32_ge_u },
        .{ .op = .br_if, .operand = 1 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load },
        .{ .op = .local_set, .operand = size },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = floor },
        .{ .op = .i32_ge_u },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 8 },
        .{ .op = .i32_const, .operand = 1 },
        .{ .op = .i32_and },
        .{ .op = .i32_eqz },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 4 },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_ne },
        .{ .op = .i32_and },
        .{ .op = .i32_and },
        .{ .op = .if_ },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_const, .operand = 0 },
        .{ .op = .i32_store, .operand = 4 },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_const, .operand = 0x80000000 },
        .{ .op = .i32_gt_u },
        .{ .op = .if_, .operand = 0x7f },
        .{ .op = .i32_const, .operand = 160 },
        .{ .op = .else_ },
        .{ .op = .i32_const, .operand = 32 },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_ctz },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_shl },
        .{ .op = .i32_add },
        .{ .op = .end },
        .{ .op = .local_set, .operand = bin },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = bin },
        .{ .op = .i32_load },
        .{ .op = .i32_store, .operand = 12 },
        .{ .op = .local_get, .operand = bin },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_store },
        .{ .op = .end },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = head },
        .{ .op = .i32_load, .operand = 8 },
        .{ .op = .i32_const, .operand = 2 },
        .{ .op = .i32_and },
        .{ .op = .i32_store, .operand = 8 },
        .{ .op = .local_get, .operand = head },
        .{ .op = .local_get, .operand = size },
        .{ .op = .i32_add },
        .{ .op = .local_set, .operand = head },
        .{ .op = .br, .operand = 0 },
        .{ .op = .end },
        .{ .op = .end },
        .{ .op = .local_get, .operand = root },
    };
    try module.emitSlice(arena.collect, &code);
}
